#!/usr/bin/env python3
"""Build the pinned JNI bridge for all packaged ABIs; requires NDK 29 and API 26.

Default host: x86_64 Linux. For QEMU hosts supply --runner as a shell-quoted
command prefix; child linker execution uses an autogenerated runner wrapper.
Archives may be supplied offline using --archive-dir (names below); otherwise
pinned upstream archives are fetched and SHA256 checked. No binary dependency
is replaced: only libplayer.so is installed after every ABI succeeds.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tarfile
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / 'app/build/native'
BRIDGE = ROOT / 'native/bridge'
LOCK = json.loads((ROOT / 'native/sources.lock.json').read_text())
ABIS = {
 'arm64-v8a': ('aarch64-linux-android', 'aarch64-linux-android', 'aarch64'),
 'armeabi-v7a': ('armv7a-linux-androideabi', 'arm-linux-androideabi', 'arm'),
 'x86_64': ('x86_64-linux-android', 'x86_64-linux-android', 'x86_64'),
}

def source(name: str, archive_dir: Path | None) -> Path:
    pin = next(s for s in LOCK['sources'] if s['name'] == name)
    filename, url, expected = pin['filename'], pin['url'], pin['sha256']
    archive = (archive_dir or CACHE / 'archives') / filename
    if not archive.exists():
        if archive_dir:
            raise RuntimeError(f'missing offline archive {archive}')
        archive.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(url) as response, archive.open('wb') as out:
            shutil.copyfileobj(response, out)
    with archive.open('rb') as f:
        actual = hashlib.file_digest(f, 'sha256').hexdigest()
    if actual != expected:
        raise RuntimeError(f'SHA256 mismatch: {archive}: {actual}; expected {expected}')
    dest = CACHE / 'sources' / name
    marker = dest / '.archive-sha256'
    if not marker.exists() or marker.read_text().strip() != expected:
        if dest.exists():
            shutil.rmtree(dest)
        dest.mkdir(parents=True)
        with tarfile.open(archive) as tf:
            tf.extractall(dest, filter='data')
        marker.write_text(expected + '\n')
    roots = [p for p in dest.iterdir() if p.is_dir()]
    if len(roots) != 1:
        raise RuntimeError(f'expected a single source root in {archive}')
    return roots[0]

def run(args: list[str], cwd: Path) -> None:
    print('+ ' + shlex.join(args), flush=True)
    subprocess.run(args, cwd=cwd, check=True)

def wrapper(path: Path, command: list[str]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('#!/bin/sh\nexec ' + shlex.join(command) + ' "$@"\n')
    path.chmod(0o755)
    return path

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ndk', type=Path, default=Path(os.environ.get('ANDROID_NDK_HOME', '/opt/android-sdk/ndk/29.0.14206865')))
    parser.add_argument('--archive-dir', type=Path)
    parser.add_argument('--runner', default='', help='shell-quoted NDK executable command prefix')
    parser.add_argument('--linker-wrapper', type=Path, help='optional executable accepting ld.lld arguments')
    args = parser.parse_args()
    ndk = args.ndk.resolve()
    properties = (ndk / 'source.properties').read_text()
    if '29.0.14206865' not in properties:
        raise RuntimeError('requires pinned Android NDK 29.0.14206865')
    toolchain = ndk / 'toolchains/llvm/prebuilt/linux-x86_64'
    tools = toolchain / 'bin'
    runner = shlex.split(args.runner)
    if not runner and os.uname().machine != 'x86_64':
        raise RuntimeError('non-x86 host requires explicit --runner')
    source('jni', args.archive_dir)
    mpv = source('mpv', args.archive_dir)
    ffmpeg = source('ffmpeg', args.archive_dir)
    linker = args.linker_wrapper.resolve() if args.linker_wrapper else wrapper(CACHE / 'tools/ld.lld', runner + [str(tools / 'ld.lld')])
    for abi, (clang_triple, lib_triple, arch) in ABIS.items():
        output = CACHE / abi
        output.mkdir(parents=True, exist_ok=True)
        libs = ROOT / 'app/src/main/jniLibs' / abi
        for dependency in ('mpv', 'avformat', 'avcodec', 'avutil', 'swscale', 'c++_shared'):
            if not (libs / f'lib{dependency}.so').is_file():
                raise RuntimeError(f'missing packaged dependency {abi}: {dependency}')
        # Use in-process frontends for single-input configuration probes.
        cc = wrapper(output / 'cc', runner + [str(tools / 'clang'), '-fintegrated-cc1', f'--target={clang_triple}26', f'--ld-path={linker}'])
        cxx = runner + [str(tools / 'clang++'), '-fintegrated-cc1', f'--target={clang_triple}26', f'--ld-path={linker}']
        config = output / 'ffmpeg-config'
        config.mkdir(exist_ok=True)
        # Real FFmpeg configure produces public avconfig.h; no FFmpeg code is built.
        run([str(ffmpeg / 'configure'), '--target-os=android', f'--arch={arch}', '--enable-cross-compile', f'--cc={cc}', '--disable-everything', '--disable-autodetect', '--disable-programs', '--disable-doc', '--disable-x86asm', '--disable-inline-asm', '--disable-asm'], config)
        cmd = cxx + ['-std=c++11', '-O2', '-fPIC', '-shared', '-nostdlib++', '-Wl,-soname,libplayer.so', '-Wl,--no-undefined', '-I', str(mpv / 'include'), '-I', str(config), '-I', str(ffmpeg)]
        cmd += [str(BRIDGE / f'{name}.cpp') for name in ('main', 'render', 'log', 'jni_utils', 'property', 'event', 'thumbnail', 'media_probe')]
        # Explicit path prevents accidentally linking the NDK libc++ instead
        # of the libc++_shared packaged beside the retained dependencies.
        cmd += ['-L', str(libs), '-lmpv', '-lavformat', '-lavcodec', '-lavutil', '-lswscale', str(libs / 'libc++_shared.so'), '-llog', '-latomic', '-landroid', '-o', str(output / 'libplayer.so')]
        run(cmd, ROOT)
    for abi in ABIS:
        shutil.copy2(CACHE / abi / 'libplayer.so', ROOT / 'app/src/main/jniLibs' / abi / 'libplayer.so')

if __name__ == '__main__':
    main()
